PLATFORM=$1
ENV=${2:-dev}

# Test Data Configuration - Update these values as needed
TC0360_EMAILFIELD_VALUE="user@example.com"
TC0360_EMAILFIELD_LONG_VALUE="user@example.com"
TC0360_EMAILFIELD_SPECIAL_VALUE="user@example.com"
TC4101_PASSWORDFIELD_VALUE="Passw0rd!"
TC4101_PASSWORDFIELD_LONG_VALUE="Passw0rd!"
TC4101_PASSWORDFIELD_SPECIAL_VALUE="Passw0rd!"
TC7706_EMAILFIELD_INPUT="user@example.com"
TC7706_PASSWORDFIELD_INPUT="Passw0rd!"
TC7185_INTITLE_VALUE="The Pragmatic Programmer"
TC7185_INTITLE_LONG_VALUE="The Pragmatic Programmer"
TC7185_INTITLE_SPECIAL_VALUE="The Pragmatic Programmer"
TC6053_DDAUTHOR_DROPDOWN_OPTION="Andy Hunt"
TC1695_INEDITION_VALUE="1st Edition"
TC1695_INEDITION_LONG_VALUE="1st Edition"
TC1695_INEDITION_SPECIAL_VALUE="1st Edition"
TC7124_INPUBLISHER_VALUE="Addison-Wesley"
TC7124_INPUBLISHER_LONG_VALUE="Addison-Wesley"
TC7124_INPUBLISHER_SPECIAL_VALUE="Addison-Wesley"
TC9287_DDFORMAT_DROPDOWN_OPTION="Hardcover"
TC4457_INISBN10_VALUE="020161622X"
TC4457_INISBN10_LONG_VALUE="020161622X"
TC4457_INISBN10_SPECIAL_VALUE="020161622X"
TC6692_INISBN13_VALUE="9780201616224"
TC6692_INISBN13_LONG_VALUE="9780201616224"
TC6692_INISBN13_SPECIAL_VALUE="9780201616224"
TC9398_DDLANGUAGE_DROPDOWN_OPTION="English"
TC5833_INPAGES_VALUE="352"
TC5833_INPAGES_LONG_VALUE="352"
TC5833_INPAGES_SPECIAL_VALUE="352"
TC7582_DDREADSTATUS_DROPDOWN_OPTION="Completed"
TC0733_INTAGS_VALUE="programming, software engineering"
TC0733_INTAGS_LONG_VALUE="programming, software engineering"
TC0733_INTAGS_SPECIAL_VALUE="programming, software engineering"
TC8780_INREVIEW_VALUE="An excellent resource with practical insights."
TC8780_INREVIEW_LONG_VALUE="An excellent resource with practical insights."
TC8780_INREVIEW_SPECIAL_VALUE="An excellent resource with practical insights."
TC1755_INFULLNAME_VALUE="Frank Herbert"
TC1755_INFULLNAME_LONG_VALUE="Frank Herbert"
TC1755_INFULLNAME_SPECIAL_VALUE="Frank Herbert"
TC3055_INFIRSTNAME_VALUE="Frank"
TC3055_INFIRSTNAME_LONG_VALUE="Frank"
TC3055_INFIRSTNAME_SPECIAL_VALUE="Frank"
TC9739_INLASTNAME_VALUE="Herbert"
TC9739_INLASTNAME_LONG_VALUE="Herbert"
TC9739_INLASTNAME_SPECIAL_VALUE="Herbert"
TC0661_INPENNAME_VALUE="F. Herbert"
TC0661_INPENNAME_LONG_VALUE="F. Herbert"
TC0661_INPENNAME_SPECIAL_VALUE="F. Herbert"
TC1465_DDCOUNTRY_DROPDOWN_OPTION="United States"
TC5696_INNATIONALITY_VALUE="American"
TC5696_INNATIONALITY_LONG_VALUE="American"
TC5696_INNATIONALITY_SPECIAL_VALUE="American"
TC2238_INBIO_VALUE="American science-fiction author best known for the Dune series."
TC2238_INBIO_LONG_VALUE="American science-fiction author best known for the Dune series."
TC2238_INBIO_SPECIAL_VALUE="American science-fiction author best known for the Dune series."
TC6363_INNOTES_VALUE="Noted for world-building and ecological themes."
TC6363_INNOTES_LONG_VALUE="Noted for world-building and ecological themes."
TC6363_INNOTES_SPECIAL_VALUE="Noted for world-building and ecological themes."
TC7790_EMAILFIELD_VALUE="newuser@example.com"
TC7790_EMAILFIELD_LONG_VALUE="newuser@example.com"
TC7790_EMAILFIELD_SPECIAL_VALUE="newuser@example.com"
TC2712_PASSWORDFIELD_VALUE="NewPassw0rd!"
TC2712_PASSWORDFIELD_LONG_VALUE="NewPassw0rd!"
TC2712_PASSWORDFIELD_SPECIAL_VALUE="NewPassw0rd!"
TC5920_EMAILFIELD_INPUT="newuser@example.com"
TC5920_PASSWORDFIELD_INPUT="NewPassw0rd!"

# Set environment-specific variables
case "$ENV" in
dev)
	ANDROID_APP_ID="com.booklistapp.dev"
	IOS_APP_ID="org.reactjs.native.example.booklistapp"
	APK_PATH="app/build/outputs/apk/development/debug/app-development-debug.apk"
	SCHEME="booklistapp-Development"
	;;
staging)
	ANDROID_APP_ID="com.booklistapp.staging"
	IOS_APP_ID="org.reactjs.native.example.booklistappStaging"
	APK_PATH="app/build/outputs/apk/staging/debug/app-staging-debug.apk"
	SCHEME="testApp-Staging"
	;;
prod)
	ANDROID_APP_ID="com.booklistapp"
	IOS_APP_ID="org.reactjs.native.example.booklistapp"
	APK_PATH="app/build/outputs/apk/release/app-release.apk"
	SCHEME="booklistapp"
	;;
*)
	echo "Unknown environment: $ENV"
	exit 1
	;;
esac

if [ "$PLATFORM" == "android" ]; then
	cd android
	echo "🛠️  Building APK..."
	case "$ENV" in
	dev)
		./gradlew assembleDevelopmentDebug
		;;
	staging)
		./gradlew assembleStagingDebug
		;;
	prod)
		./gradlew assembleRelease
		;;
	esac
	echo "📱 Installing APK..."
	adb install -r "$APK_PATH"
	cd ..
	echo "⌨️  Disabling virtual keyboard..."
	adb shell settings put secure show_ime_with_hard_keyboard 0
	adb shell ime disable com.android.inputmethod.latin/.LatinIME 2>/dev/null || true
	echo "🚀 Running Master Test Suite on Android..."
	maestro test e2e/master_suite.yaml \
		--env APP_ID="$ANDROID_APP_ID" \
		--env TC0360_EMAILFIELD_VALUE="$TC0360_EMAILFIELD_VALUE" \
		--env TC0360_EMAILFIELD_LONG_VALUE="$TC0360_EMAILFIELD_LONG_VALUE" \
		--env TC0360_EMAILFIELD_SPECIAL_VALUE="$TC0360_EMAILFIELD_SPECIAL_VALUE" \
		--env TC4101_PASSWORDFIELD_VALUE="$TC4101_PASSWORDFIELD_VALUE" \
		--env TC4101_PASSWORDFIELD_LONG_VALUE="$TC4101_PASSWORDFIELD_LONG_VALUE" \
		--env TC4101_PASSWORDFIELD_SPECIAL_VALUE="$TC4101_PASSWORDFIELD_SPECIAL_VALUE" \
		--env TC7706_EMAILFIELD_INPUT="$TC7706_EMAILFIELD_INPUT" \
		--env TC7706_PASSWORDFIELD_INPUT="$TC7706_PASSWORDFIELD_INPUT" \
		--env TC7185_INTITLE_VALUE="$TC7185_INTITLE_VALUE" \
		--env TC7185_INTITLE_LONG_VALUE="$TC7185_INTITLE_LONG_VALUE" \
		--env TC7185_INTITLE_SPECIAL_VALUE="$TC7185_INTITLE_SPECIAL_VALUE" \
		--env TC6053_DDAUTHOR_DROPDOWN_OPTION="$TC6053_DDAUTHOR_DROPDOWN_OPTION" \
		--env TC1695_INEDITION_VALUE="$TC1695_INEDITION_VALUE" \
		--env TC1695_INEDITION_LONG_VALUE="$TC1695_INEDITION_LONG_VALUE" \
		--env TC1695_INEDITION_SPECIAL_VALUE="$TC1695_INEDITION_SPECIAL_VALUE" \
		--env TC7124_INPUBLISHER_VALUE="$TC7124_INPUBLISHER_VALUE" \
		--env TC7124_INPUBLISHER_LONG_VALUE="$TC7124_INPUBLISHER_LONG_VALUE" \
		--env TC7124_INPUBLISHER_SPECIAL_VALUE="$TC7124_INPUBLISHER_SPECIAL_VALUE" \
		--env TC9287_DDFORMAT_DROPDOWN_OPTION="$TC9287_DDFORMAT_DROPDOWN_OPTION" \
		--env TC4457_INISBN10_VALUE="$TC4457_INISBN10_VALUE" \
		--env TC4457_INISBN10_LONG_VALUE="$TC4457_INISBN10_LONG_VALUE" \
		--env TC4457_INISBN10_SPECIAL_VALUE="$TC4457_INISBN10_SPECIAL_VALUE" \
		--env TC6692_INISBN13_VALUE="$TC6692_INISBN13_VALUE" \
		--env TC6692_INISBN13_LONG_VALUE="$TC6692_INISBN13_LONG_VALUE" \
		--env TC6692_INISBN13_SPECIAL_VALUE="$TC6692_INISBN13_SPECIAL_VALUE" \
		--env TC9398_DDLANGUAGE_DROPDOWN_OPTION="$TC9398_DDLANGUAGE_DROPDOWN_OPTION" \
		--env TC5833_INPAGES_VALUE="$TC5833_INPAGES_VALUE" \
		--env TC5833_INPAGES_LONG_VALUE="$TC5833_INPAGES_LONG_VALUE" \
		--env TC5833_INPAGES_SPECIAL_VALUE="$TC5833_INPAGES_SPECIAL_VALUE" \
		--env TC7582_DDREADSTATUS_DROPDOWN_OPTION="$TC7582_DDREADSTATUS_DROPDOWN_OPTION" \
		--env TC0733_INTAGS_VALUE="$TC0733_INTAGS_VALUE" \
		--env TC0733_INTAGS_LONG_VALUE="$TC0733_INTAGS_LONG_VALUE" \
		--env TC0733_INTAGS_SPECIAL_VALUE="$TC0733_INTAGS_SPECIAL_VALUE" \
		--env TC8780_INREVIEW_VALUE="$TC8780_INREVIEW_VALUE" \
		--env TC8780_INREVIEW_LONG_VALUE="$TC8780_INREVIEW_LONG_VALUE" \
		--env TC8780_INREVIEW_SPECIAL_VALUE="$TC8780_INREVIEW_SPECIAL_VALUE" \
		--env TC1755_INFULLNAME_VALUE="$TC1755_INFULLNAME_VALUE" \
		--env TC1755_INFULLNAME_LONG_VALUE="$TC1755_INFULLNAME_LONG_VALUE" \
		--env TC1755_INFULLNAME_SPECIAL_VALUE="$TC1755_INFULLNAME_SPECIAL_VALUE" \
		--env TC3055_INFIRSTNAME_VALUE="$TC3055_INFIRSTNAME_VALUE" \
		--env TC3055_INFIRSTNAME_LONG_VALUE="$TC3055_INFIRSTNAME_LONG_VALUE" \
		--env TC3055_INFIRSTNAME_SPECIAL_VALUE="$TC3055_INFIRSTNAME_SPECIAL_VALUE" \
		--env TC9739_INLASTNAME_VALUE="$TC9739_INLASTNAME_VALUE" \
		--env TC9739_INLASTNAME_LONG_VALUE="$TC9739_INLASTNAME_LONG_VALUE" \
		--env TC9739_INLASTNAME_SPECIAL_VALUE="$TC9739_INLASTNAME_SPECIAL_VALUE" \
		--env TC0661_INPENNAME_VALUE="$TC0661_INPENNAME_VALUE" \
		--env TC0661_INPENNAME_LONG_VALUE="$TC0661_INPENNAME_LONG_VALUE" \
		--env TC0661_INPENNAME_SPECIAL_VALUE="$TC0661_INPENNAME_SPECIAL_VALUE" \
		--env TC1465_DDCOUNTRY_DROPDOWN_OPTION="$TC1465_DDCOUNTRY_DROPDOWN_OPTION" \
		--env TC5696_INNATIONALITY_VALUE="$TC5696_INNATIONALITY_VALUE" \
		--env TC5696_INNATIONALITY_LONG_VALUE="$TC5696_INNATIONALITY_LONG_VALUE" \
		--env TC5696_INNATIONALITY_SPECIAL_VALUE="$TC5696_INNATIONALITY_SPECIAL_VALUE" \
		--env TC2238_INBIO_VALUE="$TC2238_INBIO_VALUE" \
		--env TC2238_INBIO_LONG_VALUE="$TC2238_INBIO_LONG_VALUE" \
		--env TC2238_INBIO_SPECIAL_VALUE="$TC2238_INBIO_SPECIAL_VALUE" \
		--env TC6363_INNOTES_VALUE="$TC6363_INNOTES_VALUE" \
		--env TC6363_INNOTES_LONG_VALUE="$TC6363_INNOTES_LONG_VALUE" \
		--env TC6363_INNOTES_SPECIAL_VALUE="$TC6363_INNOTES_SPECIAL_VALUE" \
		--env TC7790_EMAILFIELD_VALUE="$TC7790_EMAILFIELD_VALUE" \
		--env TC7790_EMAILFIELD_LONG_VALUE="$TC7790_EMAILFIELD_LONG_VALUE" \
		--env TC7790_EMAILFIELD_SPECIAL_VALUE="$TC7790_EMAILFIELD_SPECIAL_VALUE" \
		--env TC2712_PASSWORDFIELD_VALUE="$TC2712_PASSWORDFIELD_VALUE" \
		--env TC2712_PASSWORDFIELD_LONG_VALUE="$TC2712_PASSWORDFIELD_LONG_VALUE" \
		--env TC2712_PASSWORDFIELD_SPECIAL_VALUE="$TC2712_PASSWORDFIELD_SPECIAL_VALUE" \
		--env TC5920_EMAILFIELD_INPUT="$TC5920_EMAILFIELD_INPUT" \
		--env TC5920_PASSWORDFIELD_INPUT="$TC5920_PASSWORDFIELD_INPUT" |
		tee maestro-detailed-output.log

	# Convert XML to JSON
	echo "📊 Parsing Maestro log to JSON..."
	node parseMaestroLog.js maestro-detailed-output.log

	# Generate comprehensive test reports
	echo "📈 Generating comprehensive test reports..."
	node generateTestReport.js e2e/master_suite.yaml e2e maestro-detailed-output.log test-reports test-metadata.json

elif [ "$PLATFORM" == "ios" ]; then
	APP_NAME="booklistapp"
	WORKSPACE="ios/$APP_NAME.xcworkspace"
	DESTINATION="platform=iOS Simulator,name=iPhone 16 Pro"
	BUILD_DIR="ios/build"

	echo "🛠️  Building iOS app for simulator..."
	xcrun xcodebuild -workspace "$WORKSPACE" \
		-scheme "$SCHEME" \
		-configuration Development \
		-sdk iphonesimulator \
		-destination "$DESTINATION" \
		-derivedDataPath "$BUILD_DIR" \
		-build

	APP_PATH="$BUILD_DIR/Build/Products/Release-iphonesimulator/$APP_NAME.app"

	if [ ! -d "$APP_PATH" ]; then
		echo "Build failed or .app not found at $APP_PATH"
		exit 1
	fi

	echo "📱 Preparing simulator..."
	SIM_STATUS=$(xcrun simctl list | grep -A1 "iPhone 16 Pro" | grep -o "Booted")
	if [ "$SIM_STATUS" != "Booted" ]; then
		echo "🔄 Booting iPhone 16 Pro simulator..."
		xcrun simctl boot "iPhone 16 Pro"
	else
		echo "iPhone 16 Pro simulator already booted."
	fi

	echo "🔁 Restarting Simulator UI..."
	killall Simulator || true
	open -a Simulator

	echo "📲 Installing app to simulator..."
	xcrun simctl install booted "$APP_PATH"

	echo "🚀 Launching app..."
	xcrun simctl launch booted org.reactjs.native.example.booklistapp

	echo "✅ Running Master Test Suite on iOS..."
	maestro test e2e/master_suite.yaml \
		--env APP_ID="$IOS_APP_ID" \
		--env TC0360_EMAILFIELD_VALUE="$TC0360_EMAILFIELD_VALUE" \
		--env TC0360_EMAILFIELD_LONG_VALUE="$TC0360_EMAILFIELD_LONG_VALUE" \
		--env TC0360_EMAILFIELD_SPECIAL_VALUE="$TC0360_EMAILFIELD_SPECIAL_VALUE" \
		--env TC4101_PASSWORDFIELD_VALUE="$TC4101_PASSWORDFIELD_VALUE" \
		--env TC4101_PASSWORDFIELD_LONG_VALUE="$TC4101_PASSWORDFIELD_LONG_VALUE" \
		--env TC4101_PASSWORDFIELD_SPECIAL_VALUE="$TC4101_PASSWORDFIELD_SPECIAL_VALUE" \
		--env TC7706_EMAILFIELD_INPUT="$TC7706_EMAILFIELD_INPUT" \
		--env TC7706_PASSWORDFIELD_INPUT="$TC7706_PASSWORDFIELD_INPUT" \
		--env TC7185_INTITLE_VALUE="$TC7185_INTITLE_VALUE" \
		--env TC7185_INTITLE_LONG_VALUE="$TC7185_INTITLE_LONG_VALUE" \
		--env TC7185_INTITLE_SPECIAL_VALUE="$TC7185_INTITLE_SPECIAL_VALUE" \
		--env TC6053_DDAUTHOR_DROPDOWN_OPTION="$TC6053_DDAUTHOR_DROPDOWN_OPTION" \
		--env TC1695_INEDITION_VALUE="$TC1695_INEDITION_VALUE" \
		--env TC1695_INEDITION_LONG_VALUE="$TC1695_INEDITION_LONG_VALUE" \
		--env TC1695_INEDITION_SPECIAL_VALUE="$TC1695_INEDITION_SPECIAL_VALUE" \
		--env TC7124_INPUBLISHER_VALUE="$TC7124_INPUBLISHER_VALUE" \
		--env TC7124_INPUBLISHER_LONG_VALUE="$TC7124_INPUBLISHER_LONG_VALUE" \
		--env TC7124_INPUBLISHER_SPECIAL_VALUE="$TC7124_INPUBLISHER_SPECIAL_VALUE" \
		--env TC9287_DDFORMAT_DROPDOWN_OPTION="$TC9287_DDFORMAT_DROPDOWN_OPTION" \
		--env TC4457_INISBN10_VALUE="$TC4457_INISBN10_VALUE" \
		--env TC4457_INISBN10_LONG_VALUE="$TC4457_INISBN10_LONG_VALUE" \
		--env TC4457_INISBN10_SPECIAL_VALUE="$TC4457_INISBN10_SPECIAL_VALUE" \
		--env TC6692_INISBN13_VALUE="$TC6692_INISBN13_VALUE" \
		--env TC6692_INISBN13_LONG_VALUE="$TC6692_INISBN13_LONG_VALUE" \
		--env TC6692_INISBN13_SPECIAL_VALUE="$TC6692_INISBN13_SPECIAL_VALUE" \
		--env TC9398_DDLANGUAGE_DROPDOWN_OPTION="$TC9398_DDLANGUAGE_DROPDOWN_OPTION" \
		--env TC5833_INPAGES_VALUE="$TC5833_INPAGES_VALUE" \
		--env TC5833_INPAGES_LONG_VALUE="$TC5833_INPAGES_LONG_VALUE" \
		--env TC5833_INPAGES_SPECIAL_VALUE="$TC5833_INPAGES_SPECIAL_VALUE" \
		--env TC7582_DDREADSTATUS_DROPDOWN_OPTION="$TC7582_DDREADSTATUS_DROPDOWN_OPTION" \
		--env TC0733_INTAGS_VALUE="$TC0733_INTAGS_VALUE" \
		--env TC0733_INTAGS_LONG_VALUE="$TC0733_INTAGS_LONG_VALUE" \
		--env TC0733_INTAGS_SPECIAL_VALUE="$TC0733_INTAGS_SPECIAL_VALUE" \
		--env TC8780_INREVIEW_VALUE="$TC8780_INREVIEW_VALUE" \
		--env TC8780_INREVIEW_LONG_VALUE="$TC8780_INREVIEW_LONG_VALUE" \
		--env TC8780_INREVIEW_SPECIAL_VALUE="$TC8780_INREVIEW_SPECIAL_VALUE" \
		--env TC1755_INFULLNAME_VALUE="$TC1755_INFULLNAME_VALUE" \
		--env TC1755_INFULLNAME_LONG_VALUE="$TC1755_INFULLNAME_LONG_VALUE" \
		--env TC1755_INFULLNAME_SPECIAL_VALUE="$TC1755_INFULLNAME_SPECIAL_VALUE" \
		--env TC3055_INFIRSTNAME_VALUE="$TC3055_INFIRSTNAME_VALUE" \
		--env TC3055_INFIRSTNAME_LONG_VALUE="$TC3055_INFIRSTNAME_LONG_VALUE" \
		--env TC3055_INFIRSTNAME_SPECIAL_VALUE="$TC3055_INFIRSTNAME_SPECIAL_VALUE" \
		--env TC9739_INLASTNAME_VALUE="$TC9739_INLASTNAME_VALUE" \
		--env TC9739_INLASTNAME_LONG_VALUE="$TC9739_INLASTNAME_LONG_VALUE" \
		--env TC9739_INLASTNAME_SPECIAL_VALUE="$TC9739_INLASTNAME_SPECIAL_VALUE" \
		--env TC0661_INPENNAME_VALUE="$TC0661_INPENNAME_VALUE" \
		--env TC0661_INPENNAME_LONG_VALUE="$TC0661_INPENNAME_LONG_VALUE" \
		--env TC0661_INPENNAME_SPECIAL_VALUE="$TC0661_INPENNAME_SPECIAL_VALUE" \
		--env TC1465_DDCOUNTRY_DROPDOWN_OPTION="$TC1465_DDCOUNTRY_DROPDOWN_OPTION" \
		--env TC5696_INNATIONALITY_VALUE="$TC5696_INNATIONALITY_VALUE" \
		--env TC5696_INNATIONALITY_LONG_VALUE="$TC5696_INNATIONALITY_LONG_VALUE" \
		--env TC5696_INNATIONALITY_SPECIAL_VALUE="$TC5696_INNATIONALITY_SPECIAL_VALUE" \
		--env TC2238_INBIO_VALUE="$TC2238_INBIO_VALUE" \
		--env TC2238_INBIO_LONG_VALUE="$TC2238_INBIO_LONG_VALUE" \
		--env TC2238_INBIO_SPECIAL_VALUE="$TC2238_INBIO_SPECIAL_VALUE" \
		--env TC6363_INNOTES_VALUE="$TC6363_INNOTES_VALUE" \
		--env TC6363_INNOTES_LONG_VALUE="$TC6363_INNOTES_LONG_VALUE" \
		--env TC6363_INNOTES_SPECIAL_VALUE="$TC6363_INNOTES_SPECIAL_VALUE" \
		--env TC7790_EMAILFIELD_VALUE="$TC7790_EMAILFIELD_VALUE" \
		--env TC7790_EMAILFIELD_LONG_VALUE="$TC7790_EMAILFIELD_LONG_VALUE" \
		--env TC7790_EMAILFIELD_SPECIAL_VALUE="$TC7790_EMAILFIELD_SPECIAL_VALUE" \
		--env TC2712_PASSWORDFIELD_VALUE="$TC2712_PASSWORDFIELD_VALUE" \
		--env TC2712_PASSWORDFIELD_LONG_VALUE="$TC2712_PASSWORDFIELD_LONG_VALUE" \
		--env TC2712_PASSWORDFIELD_SPECIAL_VALUE="$TC2712_PASSWORDFIELD_SPECIAL_VALUE" \
		--env TC5920_EMAILFIELD_INPUT="$TC5920_EMAILFIELD_INPUT" \
		--env TC5920_PASSWORDFIELD_INPUT="$TC5920_PASSWORDFIELD_INPUT" |
		tee maestro-detailed-output.log

	# Generate comprehensive test reports
	echo "📈 Generating comprehensive test reports..."
	node generateTestReport.js e2e/master_suite.yaml e2e maestro-detailed-output.log test-reports test-metadata.json

else
	echo "Usage: $0 [android|ios]"
	exit 1
fi
