import React from 'react';
import { StyleProp } from 'react-native';
import { text } from '@/assets';
import { sharedStyles } from '@/components/shared/sharedStyles';
import { ASBadge } from '@/components';

type Props = React.ComponentProps<typeof ASBadge> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASBadge.
 *
 * Applies the structural props that are constant across every ASBadge
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASBadge directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppBadge: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASBadge
    badgeStyles={sharedStyles.authorCountryBadgeBadgeStyles}
    badgeTextStyle={[text.body.small, sharedStyles.authorCountryBadgeBadgeText]}
    containerStyle={sharedStyles.authorCountryBadgeContainer}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppBadge;
