import React from 'react';
import { StyleProp } from 'react-native';
import { color, text } from '@/assets';
import { sharedStyles } from '@/components/shared/sharedStyles';
import { ASDatePicker } from '@/components';

type Props = React.ComponentProps<typeof ASDatePicker> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASDatePicker.
 *
 * Applies the structural props that are constant across every ASDatePicker
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASDatePicker directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppDatePicker: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASDatePicker
    placeholderTextColor={color.text.tertiary}
    borderActiveColor={color.brand.primary}
    borderErrorColor={color.status.danger}
    isDefaultCurrentDate={false}
    selectedDateFormat={'yyyy-MM-dd'}
    suffixIcon={'calendar_month'}
    defaultDate={false}
    displayDateFormat={'yyyy-MM-dd'}
    labelTextStyle={[text.label.medium, sharedStyles.dpAcquiredLabelText]}
    iconStyles={sharedStyles.dpAcquiredIconStyles}
    errorMessageTextStyle={[
      text.label.small,
      sharedStyles.emailFieldErrorMessageText,
    ]}
    inputTextStyle={[text.body.medium, sharedStyles.dpAcquiredInputText]}
    prefixTextStyle={[text.body.medium, sharedStyles.emailFieldPrefixText]}
    containerStyle={sharedStyles.dpAcquiredContainer}
    undefined={sharedStyles.dpAcquiredUndefined}
    calendarPopupStyles={sharedStyles.dpAcquiredCalendarPopupStyles}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppDatePicker;
