import React from 'react';
import { StyleProp } from 'react-native';
import { color, component, text } from '@/assets';
import { sharedStyles } from '@/components/shared/sharedStyles';
import { ASFloatingActionButton } from '@/components';

type Props = React.ComponentProps<typeof ASFloatingActionButton> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASFloatingActionButton.
 *
 * Applies the structural props that are constant across every ASFloatingActionButton
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASFloatingActionButton directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppFloatingActionButton: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASFloatingActionButton
    floatingPosition={'bottom-right'}
    iconSize={component.icon.size.sm}
    iconColor={color.brand.onPrimary}
    containerHardCodeStyle={sharedStyles.btnAddAuthorContainerHardCode}
    textStyle={[text.title.small, sharedStyles.btnAddAuthorText]}
    iconStyles={sharedStyles.btnAddAuthorIconStyles}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppFloatingActionButton;
