import React from 'react';
import { StyleProp } from 'react-native';
import { color, text } from '@/assets';
import { sharedStyles } from '@/components/shared/sharedStyles';
import { ASPasswordTextField } from '@/components';

type Props = React.ComponentProps<typeof ASPasswordTextField> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASPasswordTextField.
 *
 * Applies the structural props that are constant across every ASPasswordTextField
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASPasswordTextField directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppPasswordTextField: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASPasswordTextField
    borderErrorColor={color.status.danger}
    placeholderTextColor={color.text.tertiary}
    borderActiveColor={color.brand.primary}
    autoCapitalize={'none'}
    secureTextEntry={true}
    autoComplete={'off'}
    isShowSuffixIcon={true}
    keyboardType={'default'}
    allowFontScaling={false}
    labelTextStyle={[text.label.medium, sharedStyles.passwordFieldLabelText]}
    inputTextStyle={[text.body.medium, sharedStyles.emailFieldInputText]}
    errorMessageTextStyle={sharedStyles.emailFieldErrorMessageText}
    prefixTextStyle={[text.body.medium, sharedStyles.emailFieldPrefixText]}
    contentContainerStyle={sharedStyles.emailFieldContentContainer}
    suffixIconStyles={sharedStyles.passwordFieldSuffixIconStyles}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppPasswordTextField;
