import React from 'react';
import { StyleProp } from 'react-native';
import { sharedStyles } from '@/components/shared/sharedStyles';
import { ASSlider } from '@/components';

type Props = React.ComponentProps<typeof ASSlider> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASSlider.
 *
 * Applies the structural props that are constant across every ASSlider
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASSlider directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppSlider: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASSlider
    minimumValue={0}
    maximumValue={100}
    step={1}
    value={50}
    sliderThumbStyles={sharedStyles.ratingSliderThumbStyles}
    sliderTrackStyles={sharedStyles.ratingSliderTrackStyles}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppSlider;
