// Auto-generated by app-studio-generator.
//
// Service test for PatchAccount1106Service (init-clients shape). Unmocks the
// real service while keeping AxiosInstance dependencies replaced with
// jest.fn stubs.

jest.unmock('../../src/services/PatchAccount1106Service');

import { PatchAccount1106Service } from '../../src/services/PatchAccount1106Service';
import { describeInitClientsServiceContract } from '../helpers/init-clients-service-contract';
import { testParams, testCallArgs } from '../generated/api-fixtures';


describeInitClientsServiceContract({
  name: "PatchAccount1106Service",
  ServiceClass: PatchAccount1106Service as any,
  methodName: "patchAccount1106",
  clientKey: "membershipServiceServiceClient",
  clientSlot: "_MembershipServiceServiceClient",
  httpVerb: "patch",
  params: testParams(["accessToken","userId","userName","journeyId","title","firstName","middleName","lastName","nickName","fullName","gender","placeOfBirth","countryOfBirth","maritalStatus","dateOfBirth","email","countryCode","mobileNumber","isCitizen","isUSCitizen","nationality","status","userType","isLock","lockedBy","lockedAt","isDeleted","deletedAt","lastLoginAt","requireChangePass","isPresentAsPermAddress","createdAt","passwordExpired","updatedAt","nameSuffix","religion","ethnicity","residencyStatus","cif","highestEducation","residentialOwnershipStatus","contacts","address","addresses","listCustomFields","employmentDetails","taxDetails","memberships","orgRelationships","kycDetails","amlDetails","apps","listRoles","permissions","segments","creditDetails","devices","userPreference","entitlements","roles"]),
  responseData: {},
  expectedCall: testCallArgs("/users/test-userId", { withBody: true }),
});
