// Auto-generated by app-studio-generator.
//
// Service test for SignInWithEmailPasswordV101101Service (helper-module shape). Unmocks the
// real service while keeping AxiosInstance dependencies replaced with
// jest.fn stubs.

jest.unmock('../../src/services/SignInWithEmailPasswordV101101Service');

// Auth services pull their axios instance from a helper module
// (`authApiClient.getApiClient()`) instead of via initClients.
// Mock the helper to return our stub so the service hits jest.fn instead
// of the real network client. The factory body is shared across every
// helper-module service test via `buildHelperModuleMock` (loaded inside
// the factory because jest.mock is hoisted above imports).
jest.mock("../../src/services/api-clients/AuthApiClient", () => {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { buildHelperModuleMock } = require('../helpers/service-test-utils');
  return buildHelperModuleMock("authApiClient");
});

import { signInWithEmailPasswordV101101Service } from '../../src/services/SignInWithEmailPasswordV101101Service';
import { MockAxios } from '../helpers/service-test-utils';
// Pull the per-test stub back out of the mocked helper module so we can
// drive `<verb>.mockResolvedValueOnce(...)` from inside each test.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const helperMod: any = require("../../src/services/api-clients/AuthApiClient");
const helperStub: any = helperMod.__stub;
import { describeHelperModuleServiceContract } from '../helpers/helper-module-service-contract';
import { testParams, testCallArgs } from '../generated/api-fixtures';


describeHelperModuleServiceContract({
  name: "SignInWithEmailPasswordV101101Service",
  serviceSingleton: signInWithEmailPasswordV101101Service as unknown,
  methodName: "signInWithEmailPasswordV101101",
  helperStub: helperStub as MockAxios,
  httpVerb: "post",
  params: testParams(["email","password"]),
  responseData: {"session":{"access_token":"mock-accessToken","refresh_token":"mock-refreshToken"},"user":{"id":"mock-userId","email":"mock-email"}},
  expectedCall: testCallArgs("/functions/v1/auth-service/sign-in", { withBody: true }),
  expectedResult: {"accessToken":"mock-accessToken","refreshToken":"mock-refreshToken","userId":"mock-userId","email":"mock-email"},
});
