// Auto-generated by app-studio-generator.
import React from 'react';
import { fireEvent, waitFor } from '@testing-library/react-native';
import { renderScreen } from '../render';
import { mockNavigate, mockGoBack, workflowMocks, prefillForm, pressAndAssertWorkflowError } from '../setup';
import AuthorForm from '../../src/screens/AuthorForm/AuthorForm';

// react-navigation passes `route` and `navigation` as props in production.
// Provide minimal stubs so screens that destructure `route.params` survive.
const route = { params: {}, name: 'MockRoute', key: 'mock-key' };
const navigation = { navigate: mockNavigate, goBack: mockGoBack };

const PREFILL_VALUES = {
    "inFullName": 'sample-value',
    "inFirstName": 'sample-value',
    "inLastName": 'sample-value',
    "inPenName": 'sample-value',
    "ddCountry": 'sample-value',
    "dpBirth": 'sample-value',
    "dpDeath": 'sample-value',
    "inNationality": 'sample-value',
    "inBio": 'sample-value',
    "inNotes": 'sample-value'
  };

describe('AuthorForm', () => {
  beforeEach(() => {
    workflowMocks.appContext = {
      entities: {
        author: {
          draft: {
            id: 'a1',
          },
        },
      },
    };
  });

  it('renders without crashing', () => {
  expect(() => renderScreen(<AuthorForm route={route} navigation={navigation} />)).not.toThrow();
  });

  it.each(["inFullName","inFirstName","inLastName","inPenName","inNationality","inBio","inNotes"])('updates value on changeText for %s', (testId) => {
    const screen = renderScreen(<AuthorForm route={route} navigation={navigation} />);
    const [input] = screen.queryAllByTestId(testId);
    expect(input).toBeTruthy();
    fireEvent.changeText(input, 'sample-value');
  });

  it.each(["ddCountry","dpBirth","dpDeath"])('opens %s on press', (testId) => {
    const screen = renderScreen(<AuthorForm route={route} navigation={navigation} />);
    const [target] = screen.queryAllByTestId(testId);
    expect(target).toBeTruthy();
    fireEvent.press(target);
    expect(target).toBeOnTheScreen();
  });

  it('fires onPress on btnSaveAuthor', async () => {
  const screen = renderScreen(<AuthorForm route={route} navigation={navigation} />);
  await prefillForm(PREFILL_VALUES);
  const [target] = screen.queryAllByTestId('btnSaveAuthor');
  expect(target).toBeTruthy();
  workflowMocks.patchAccount1106.mockResolvedValueOnce({});
  fireEvent.press(target);
  await waitFor(() => {
  expect(workflowMocks.patchAccount1106).toHaveBeenCalled();
  expect(workflowMocks.patchAccount1106).toHaveBeenCalledWith(
    expect.objectContaining({
      userId: 'a1',
    }),
  );
  });
  });

  it('handles error when patchAccount1106 rejects', async () => {
  const screen = renderScreen(<AuthorForm route={route} navigation={navigation} />);
  await prefillForm(PREFILL_VALUES);
  await pressAndAssertWorkflowError({
    screen,
    buttonTestId: 'btnSaveAuthor',
    workflowMock: workflowMocks.patchAccount1106,
    errorMessage: 'boom-patchAccount1106',
  });
  });

  it('fires onPress on btnCancelAuthor', async () => {
  const screen = renderScreen(<AuthorForm route={route} navigation={navigation} />);
  await prefillForm(PREFILL_VALUES);
  const [target] = screen.queryAllByTestId('btnCancelAuthor');
  expect(target).toBeTruthy();
  fireEvent.press(target);
  await waitFor(() => {
  expect(mockNavigate).toHaveBeenCalledWith('AuthorList', expect.anything());
  });
  });

});
