// Auto-generated by app-studio-generator.
import React from "react";
import { fireEvent, waitFor } from "@testing-library/react-native";
import { renderScreen } from "../render";
import { mockNavigate, mockGoBack, workflowMocks } from "../setup";
import AuthorList from "../../src/screens/AuthorList/AuthorList";

// react-navigation passes `route` and `navigation` as props in production.
// Provide minimal stubs so screens that destructure `route.params` survive.
const route = { params: {}, name: "MockRoute", key: "mock-key" };
const navigation = { navigate: mockNavigate, goBack: mockGoBack };

const authorItem = {
  id: "a1",
  authorName_item: "Andrew Hunt",
  authorCountry_item: "United States",
};

beforeEach(() => {
  workflowMocks.globalData = {
    authors: [authorItem],
  };
  workflowMocks.appContext = {
    entities: {
      author: {
        selected: null,
        draft: { stale: true },
        action: "edit",
      },
    },
  };
});

describe("AuthorList", () => {
  it("renders without crashing", () => {
    expect(() =>
      renderScreen(<AuthorList route={route} navigation={navigation} />)
    ).not.toThrow();
  });

  it("renders list container authorsList", () => {
    const screen = renderScreen(
      <AuthorList route={route} navigation={navigation} />
    );
    expect(screen.getByTestId("authorsList")).toBeOnTheScreen();
  });

  it("fires onPress on author item -> AuthorDetails", async () => {
    const screen = renderScreen(
      <AuthorList route={route} navigation={navigation} />
    );
    const [target] = screen.queryAllByTestId("authorListItemPressable");
    expect(target).toBeTruthy();
    fireEvent.press(target);
    await waitFor(() => {
      expect(mockNavigate).toHaveBeenCalledWith(
        "AuthorDetails",
        expect.anything()
      );
    });
    const [updater] = workflowMocks.setAppContext.mock.calls[0];
    const nextContext = updater(workflowMocks.appContext);
    expect(nextContext.entities.author.selected).toEqual(authorItem);
    expect(nextContext.entities.author.draft).toEqual({});
    expect(nextContext.entities.author.action).toBeNull();
  });

  it("fires onPress on btnAddAuthor", async () => {
    const screen = renderScreen(
      <AuthorList route={route} navigation={navigation} />
    );
    const [target] = screen.queryAllByTestId("btnAddAuthor");
    expect(target).toBeTruthy();
    fireEvent.press(target);
    await waitFor(() => {
      expect(mockNavigate).toHaveBeenCalledWith(
        "AuthorForm",
        expect.anything()
      );
    });
  });
});
