// Auto-generated by app-studio-generator.
import React from 'react';
import { fireEvent, waitFor } from '@testing-library/react-native';
import { renderScreen } from '../render';
import { mockNavigate, mockGoBack } from '../setup';
import AuthorDetails from '../../src/screens/AuthorDetails/AuthorDetails';

// react-navigation passes `route` and `navigation` as props in production.
// Provide minimal stubs so screens that destructure `route.params` survive.
const route = { params: {}, name: 'MockRoute', key: 'mock-key' };
const navigation = { navigate: mockNavigate, goBack: mockGoBack };


describe('AuthorDetails', () => {
  it('renders without crashing', () => {
  expect(() => renderScreen(<AuthorDetails route={route} navigation={navigation} />)).not.toThrow();
  });

  it.each([["btnEditAuthor","AuthorForm"],["btnDeleteAuthor","AuthorList"]])('fires onPress on %s -> %s', async (testId, expectedRoute) => {
    const screen = renderScreen(<AuthorDetails route={route} navigation={navigation} />);
    const [target] = screen.queryAllByTestId(testId);
    expect(target).toBeTruthy();
    fireEvent.press(target);
    await waitFor(() => {
      expect(mockNavigate).toHaveBeenCalledWith(expectedRoute, expect.anything());
    });
  });

});
