// Auto-generated by app-studio-generator.
import React from 'react';
import { fireEvent, waitFor } from '@testing-library/react-native';
import { renderScreen } from '../render';
import { mockNavigate, mockGoBack, prefillForm } from '../setup';
import BookDetails from '../../src/screens/BookDetails/BookDetails';

// react-navigation passes `route` and `navigation` as props in production.
// Provide minimal stubs so screens that destructure `route.params` survive.
const route = { params: {}, name: 'MockRoute', key: 'mock-key' };
const navigation = { navigate: mockNavigate, goBack: mockGoBack };

const PREFILL_VALUES = {
    "rating": 'sample-value'
  };

describe('BookDetails', () => {
  it('renders without crashing', () => {
  expect(() => renderScreen(<BookDetails route={route} navigation={navigation} />)).not.toThrow();
  });

  it('opens rating on press', () => {
  const screen = renderScreen(<BookDetails route={route} navigation={navigation} />);
  const [target] = screen.queryAllByTestId('rating');
  expect(target).toBeTruthy();
  fireEvent.press(target);
  expect(target).toBeOnTheScreen();
  });

  it.each([["btnEditBook","BookForm"],["btnDeleteBook","Dashboard"]])('fires onPress on %s -> %s (after prefill)', async (testId, expectedRoute) => {
    const screen = renderScreen(<BookDetails route={route} navigation={navigation} />);
    await prefillForm(PREFILL_VALUES);
    const [target] = screen.queryAllByTestId(testId);
    expect(target).toBeTruthy();
    fireEvent.press(target);
    await waitFor(() => {
      expect(mockNavigate).toHaveBeenCalledWith(expectedRoute, expect.anything());
    });
  });

});
