// Auto-generated by app-studio-generator.
import React from 'react';
import { fireEvent, waitFor } from '@testing-library/react-native';
import { renderScreen } from '../render';
import { mockNavigate, mockGoBack, prefillForm } from '../setup';
import BookForm from '../../src/screens/BookForm/BookForm';

// react-navigation passes `route` and `navigation` as props in production.
// Provide minimal stubs so screens that destructure `route.params` survive.
const route = { params: {}, name: 'MockRoute', key: 'mock-key' };
const navigation = { navigate: mockNavigate, goBack: mockGoBack };

const PREFILL_VALUES = {
    "inTitle": 'sample-value',
    "ddAuthor": 'sample-value',
    "inEdition": 'sample-value',
    "inPublisher": 'sample-value',
    "dpPublished": 'sample-value',
    "dpAcquired": 'sample-value',
    "ddFormat": 'sample-value',
    "inIsbn10": 'sample-value',
    "inIsbn13": 'sample-value',
    "ddLanguage": 'sample-value',
    "inPages": 'sample-value',
    "ddReadStatus": 'sample-value',
    "dpReadStart": 'sample-value',
    "dpReadFinish": 'sample-value',
    "slRating": 'sample-value',
    "inTags": 'sample-value',
    "inReview": 'sample-value'
  };

describe('BookForm', () => {
  it('renders without crashing', () => {
  expect(() => renderScreen(<BookForm route={route} navigation={navigation} />)).not.toThrow();
  });

  it.each(["inTitle","inEdition","inPublisher","inIsbn10","inIsbn13","inPages","inTags","inReview"])('updates value on changeText for %s', (testId) => {
    const screen = renderScreen(<BookForm route={route} navigation={navigation} />);
    const [input] = screen.queryAllByTestId(testId);
    expect(input).toBeTruthy();
    fireEvent.changeText(input, 'sample-value');
  });

  it.each(["ddAuthor","dpPublished","dpAcquired","ddFormat","ddLanguage","ddReadStatus","dpReadStart","dpReadFinish","slRating"])('opens %s on press', (testId) => {
    const screen = renderScreen(<BookForm route={route} navigation={navigation} />);
    const [target] = screen.queryAllByTestId(testId);
    expect(target).toBeTruthy();
    fireEvent.press(target);
    expect(target).toBeOnTheScreen();
  });

  it.each([["btnSaveBook","Dashboard"],["btnCancelBook","Dashboard"]])('fires onPress on %s -> %s (after prefill)', async (testId, expectedRoute) => {
    const screen = renderScreen(<BookForm route={route} navigation={navigation} />);
    await prefillForm(PREFILL_VALUES);
    const [target] = screen.queryAllByTestId(testId);
    expect(target).toBeTruthy();
    fireEvent.press(target);
    await waitFor(() => {
      expect(mockNavigate).toHaveBeenCalledWith(expectedRoute, expect.anything());
    });
  });

});
