// Auto-generated by app-studio-generator.
import React from 'react';
import { fireEvent, waitFor } from '@testing-library/react-native';
import { renderScreen } from '../render';
import { mockNavigate, mockGoBack } from '../setup';
import Dashboard from '../../src/screens/Dashboard/Dashboard';

// react-navigation passes `route` and `navigation` as props in production.
// Provide minimal stubs so screens that destructure `route.params` survive.
const route = { params: {}, name: 'MockRoute', key: 'mock-key' };
const navigation = { navigate: mockNavigate, goBack: mockGoBack };


describe('Dashboard', () => {
  it('renders without crashing', () => {
  expect(() => renderScreen(<Dashboard route={route} navigation={navigation} />)).not.toThrow();
  });

  it('renders list container booksList', () => {
  const screen = renderScreen(<Dashboard route={route} navigation={navigation} />);
  expect(screen.getByTestId('booksList')).toBeOnTheScreen();
  });

  it('fires onPress on btnAddBook', async () => {
  const screen = renderScreen(<Dashboard route={route} navigation={navigation} />);
  const [target] = screen.queryAllByTestId('btnAddBook');
  expect(target).toBeTruthy();
  fireEvent.press(target);
  await waitFor(() => {
  expect(mockNavigate).toHaveBeenCalledWith('BookForm', expect.anything());
  });
  });

});
