// Auto-generated by app-studio-generator.
import React from 'react';
import { fireEvent, waitFor } from '@testing-library/react-native';
import { renderScreen } from '../render';
import { mockNavigate, mockGoBack, workflowMocks, getLastFormikBag, prefillForm, pressAndAssertWorkflowBlocked, pressAndAssertWorkflowError } from '../setup';
import SignUp from '../../src/screens/SignUp/SignUp';

// react-navigation passes `route` and `navigation` as props in production.
// Provide minimal stubs so screens that destructure `route.params` survive.
const route = { params: {}, name: 'MockRoute', key: 'mock-key' };
const navigation = { navigate: mockNavigate, goBack: mockGoBack };

const PREFILL_VALUES = {
    "emailField": 'sample-value',
    "passwordField": 'sample-value'
  };

describe('SignUp', () => {
  it('renders without crashing', () => {
  expect(() => renderScreen(<SignUp route={route} navigation={navigation} />)).not.toThrow();
  });

  it.each(["emailField","passwordField"])('updates value on changeText for %s', (testId) => {
    const screen = renderScreen(<SignUp route={route} navigation={navigation} />);
    const [input] = screen.queryAllByTestId(testId);
    expect(input).toBeTruthy();
    fireEvent.changeText(input, 'sample-value');
  });

  it.each([["emailField","Email is required"],["passwordField","Password is required"]])('required validation on %s (%s)', async (field, _msg) => {
    const screen = renderScreen(<SignUp route={route} navigation={navigation} />);
    const bag = getLastFormikBag();
    expect(bag).toBeTruthy();
    await bag.setFieldValue(field, '');
    await bag.submitForm();
    await waitFor(() => {
      expect(screen.queryByTestId(`error-${field}`)).not.toBeNull();
    });
  });

  it('applies secureTextEntry on passwordField', () => {
  const screen = renderScreen(<SignUp route={route} navigation={navigation} />);
  const [el] = screen.queryAllByTestId('passwordField');
  expect(el).toBeTruthy();
  expect(el.props.secureTextEntry === true || el.findByProps).toBeTruthy();
  });

  it('fires onPress on signUpButton', async () => {
  const screen = renderScreen(<SignUp route={route} navigation={navigation} />);
  await prefillForm(PREFILL_VALUES);
  const [target] = screen.queryAllByTestId('signUpButton');
  expect(target).toBeTruthy();
  workflowMocks.signUpWithEmailPassword100.mockResolvedValueOnce({});
  fireEvent.press(target);
  await waitFor(() => {
  expect(workflowMocks.signUpWithEmailPassword100).toHaveBeenCalled();
  });
  });

  it('blocks workflow signUpWithEmailPassword100 when form invalid (submit-gate)', async () => {
  const screen = renderScreen(<SignUp route={route} navigation={navigation} />);
  await pressAndAssertWorkflowBlocked({
    screen,
    buttonTestId: 'signUpButton',
    workflowMock: workflowMocks.signUpWithEmailPassword100,
  });
  });

  it('handles error when signUpWithEmailPassword100 rejects', async () => {
  const screen = renderScreen(<SignUp route={route} navigation={navigation} />);
  await prefillForm(PREFILL_VALUES);
  await pressAndAssertWorkflowError({
    screen,
    buttonTestId: 'signUpButton',
    workflowMock: workflowMocks.signUpWithEmailPassword100,
    errorMessage: 'boom-signUpWithEmailPassword100',
  });
  });

});
