// Auto-generated by app-studio-generator.
//
// Context-layer test for PatchAccount1106Context. Opts out of the global
// workflow-context mock via the `@real/...` path prefix so the actual
// provider/hook body runs.
//
// The factory-style `jest.mock` is required because the provider
// captures `const xService = XService.instance()` at module scope —
// `beforeEach` mock setup would land too late.

import React from 'react';
import { renderHook, act, waitFor } from '@testing-library/react-native';
import { expectHookThrowsWithoutProvider } from '../helpers/context-contract';

// Override the global automock from setup.ts with a factory so the
// provider's module-scope service capture sees a working stub. Variables
// declared inside the factory must use the `mock` prefix (jest.mock is
// hoisted; outer-scope refs would throw out-of-scope errors).
jest.mock("../../src/services/PatchAccount1106Service", () => {
  const mockFakeMethod = jest.fn();
  return {
    PatchAccount1106Service: {
      instance: jest.fn(() => ({ patchAccount1106: mockFakeMethod })),
    },
    __fakeMethod: mockFakeMethod,
  };
});

import {
  PatchAccount1106Provider,
  usePatchAccount1106,
} from '@real/context/PatchAccount1106Context';

// Pull the per-test stub out of the mocked module so each it() can drive
// `fakeMethod.mockResolvedValueOnce(...)` etc.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const fakeMethod: jest.Mock = (
  require("../../src/services/PatchAccount1106Service") as { __fakeMethod: jest.Mock }
).__fakeMethod;

beforeEach(() => {
  fakeMethod.mockReset();
});

const wrapper: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <PatchAccount1106Provider>{children}</PatchAccount1106Provider>
);

const buildParams = (): Record<string, unknown> => ({
  "accessToken": 'test-accessToken',
  "userId": 'test-userId',
});

// Service is expected to return an object whose keys match the source
// expressions read by `set<Key>(result.<sourceKey>)` in the provider.
const buildHappyResult = (): Record<string, unknown> => ({
  responseBody: "mock-responseBody",
});

describe('PatchAccount1106Context', () => {
  expectHookThrowsWithoutProvider({
    hookName: 'usePatchAccount1106',
    providerName: 'PatchAccount1106Provider',
    useHook: () => usePatchAccount1106(),
  });

  it('initial state — responseBodyLoading is false and action is callable', () => {
    const { result } = renderHook(() => usePatchAccount1106(), { wrapper });
    expect(result.current.responseBodyLoading).toBe(false);
    expect(result.current.responseBody).toBeNull();
    expect(typeof result.current.patchAccount1106).toBe('function');
  });

  it('happy path: patchAccount1106() invokes the service and populates state', async () => {
    fakeMethod.mockResolvedValueOnce(buildHappyResult());
    const { result } = renderHook(() => usePatchAccount1106(), { wrapper });

    // NOSONAR (typescript:S1874) — act(async) is the documented RTL
    // pattern for state-updating hooks under react-test-renderer; the
    // newer overload still passes through to this signature.
    await act(async () => { // NOSONAR
      await result.current.patchAccount1106(buildParams());
    });

    expect(fakeMethod).toHaveBeenCalledTimes(1);
    expect(fakeMethod).toHaveBeenCalledWith(
      expect.objectContaining(buildParams()),
    );
    expect(result.current.responseBodyLoading).toBe(false);
    expect(result.current.responseBody).toBe(
      "mock-responseBody",
    );
  });

  it('error path: patchAccount1106() re-throws and clears responseBodyLoading', async () => {
    const boom = new Error('boom-PatchAccount1106Context');
    fakeMethod.mockRejectedValueOnce(boom);
    const { result } = renderHook(() => usePatchAccount1106(), { wrapper });

    // Silence the dev-mode `console.error('[PatchAccount1106Context] Error:', ...)`
    // the provider logs before re-throwing.
    const origConsoleError = console.error;
    console.error = () => {};
    try {
      await expect(
        act(async () => { // NOSONAR (S1874) — see comment in happy path
          await result.current.patchAccount1106(buildParams());
        }),
      ).rejects.toThrow('boom-PatchAccount1106Context');
    } finally {
      console.error = origConsoleError;
    }

    await waitFor(() => {
      expect(result.current.responseBodyLoading).toBe(false);
    });
    // Catch block must not leak partial state on rejection.
    expect(fakeMethod).toHaveBeenCalledTimes(1);
    expect(result.current.responseBody).toBeNull();
  });
});
