// Auto-generated by app-studio-generator.
//
// Context-layer test for SignInWithEmailPasswordV101101Context. Opts out of the global
// workflow-context mock via the `@real/...` path prefix so the actual
// provider/hook body runs.
//
// The factory-style `jest.mock` is required because the provider
// captures `const xService = XService.instance()` at module scope —
// `beforeEach` mock setup would land too late.

import React from 'react';
import { renderHook, act, waitFor } from '@testing-library/react-native';
import { expectHookThrowsWithoutProvider } from '../helpers/context-contract';

// Override the global automock from setup.ts with a factory so the
// provider's module-scope service capture sees a working stub. Variables
// declared inside the factory must use the `mock` prefix (jest.mock is
// hoisted; outer-scope refs would throw out-of-scope errors).
jest.mock("../../src/services/SignInWithEmailPasswordV101101Service", () => {
  const mockFakeMethod = jest.fn();
  return {
    signInWithEmailPasswordV101101Service: {
      signInWithEmailPasswordV101101: mockFakeMethod,
    },
    __fakeMethod: mockFakeMethod,
  };
});

import {
  SignInWithEmailPasswordV101101Provider,
  useSignInWithEmailPasswordV101101,
} from '@real/context/SignInWithEmailPasswordV101101Context';

// Pull the per-test stub out of the mocked module so each it() can drive
// `fakeMethod.mockResolvedValueOnce(...)` etc.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const fakeMethod: jest.Mock = (
  require("../../src/services/SignInWithEmailPasswordV101101Service") as { __fakeMethod: jest.Mock }
).__fakeMethod;

beforeEach(() => {
  fakeMethod.mockReset();
});

const wrapper: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <SignInWithEmailPasswordV101101Provider>{children}</SignInWithEmailPasswordV101101Provider>
);

const buildParams = (): Record<string, unknown> => ({
  "email": 'test-email',
  "password": 'test-password',
});

const buildHappyResult = (): Record<string, unknown> => ({});

describe('SignInWithEmailPasswordV101101Context', () => {
  expectHookThrowsWithoutProvider({
    hookName: 'useSignInWithEmailPasswordV101101',
    providerName: 'SignInWithEmailPasswordV101101Provider',
    useHook: () => useSignInWithEmailPasswordV101101(),
  });

  it('initial state — signInUserLoading is false and action is callable', () => {
    const { result } = renderHook(() => useSignInWithEmailPasswordV101101(), { wrapper });
    expect(result.current.signInUserLoading).toBe(false);
    expect(typeof result.current.signInWithEmailPasswordV101101).toBe('function');
  });

  it('happy path: signInWithEmailPasswordV101101() invokes the service', async () => {
    fakeMethod.mockResolvedValueOnce(buildHappyResult());
    const { result } = renderHook(() => useSignInWithEmailPasswordV101101(), { wrapper });

    // NOSONAR (typescript:S1874) — act(async) is the documented RTL
    // pattern for state-updating hooks under react-test-renderer; the
    // newer overload still passes through to this signature.
    await act(async () => { // NOSONAR
      await result.current.signInWithEmailPasswordV101101(buildParams());
    });

    expect(fakeMethod).toHaveBeenCalledTimes(1);
    expect(fakeMethod).toHaveBeenCalledWith(
      expect.objectContaining(buildParams()),
    );
    expect(result.current.signInUserLoading).toBe(false);
  });

  it('error path: signInWithEmailPasswordV101101() re-throws and clears signInUserLoading', async () => {
    const boom = new Error('boom-SignInWithEmailPasswordV101101Context');
    fakeMethod.mockRejectedValueOnce(boom);
    const { result } = renderHook(() => useSignInWithEmailPasswordV101101(), { wrapper });

    // Silence the dev-mode `console.error('[SignInWithEmailPasswordV101101Context] Error:', ...)`
    // the provider logs before re-throwing.
    const origConsoleError = console.error;
    console.error = () => {};
    try {
      await expect(
        act(async () => { // NOSONAR (S1874) — see comment in happy path
          await result.current.signInWithEmailPasswordV101101(buildParams());
        }),
      ).rejects.toThrow('boom-SignInWithEmailPasswordV101101Context');
    } finally {
      console.error = origConsoleError;
    }

    await waitFor(() => {
      expect(result.current.signInUserLoading).toBe(false);
    });
    // Catch block must not leak partial state on rejection.
    expect(fakeMethod).toHaveBeenCalledTimes(1);
  });
});
